INSERT INTO articulos VALUES (1,'Articulo No. 76','Los Sujetos Obligados, de acuerdo con sus facultades, funciones u objeto social, según corresponda, pondrán a disposición del público, a través de los medios electrónicos previstos en la presente Ley y de manera actualizada, la información mínima de oficio siguiente',1);
INSERT INTO articulos VALUES (2,'Articulo No. 77','Además de lo previsto en el artículo 76 de la presente Ley, el Poder Ejecutivo del Estado deberá informar de lo siguiente:',1);
INSERT INTO articulos VALUES (3,'Articulo No. 82','Además de las obligaciones establecidas en el artículo 76, las instituciones de educación superior públicas dotadas de autonomía, deberán informar lo siguiente:',1);
INSERT INTO fracciones VALUES (1,1,'Fracción I','El marco normativo aplicable al Sujeto Obligado, en el que deberá incluirse leyes, códigos, reglamentos, decretos de creación, manuales administrativos, reglas de operación, criterios, políticas, entre otros;',1);
INSERT INTO fracciones VALUES (1,2,'Fracción II','Su estructura orgánica completa, en un formato que permita vincular cada parte de la estructura, las atribuciones y responsabilidades que le corresponden a cada servidor público, prestador de servicios profesionales o miembro de los Sujetos Obligados, de conformidad con las disposiciones aplicables;',1);
INSERT INTO fracciones VALUES (1,3,'Fracción III','Las facultades de cada Área;',1);
INSERT INTO fracciones VALUES (1,4,'Fracción IV','Las metas y objetivos de las Áreas de conformidad con sus programas operativos;',1);
INSERT INTO fracciones VALUES (1,5,'Fracción V','Los indicadores relacionados con temas de interés público o trascendencia social que conforme a sus funciones, deban establecer;',1);
INSERT INTO fracciones VALUES (1,6,'Fracción VI','Los indicadores que permitan rendir cuenta de sus objetivos y resultados;',1);
INSERT INTO fracciones VALUES (1,7,'Fracción VII','El directorio de todos los Servidores Públicos, a partir del nivel de jefe de departamento o su equivalente, o de menor nivel, cuando se brinde atención al público, manejen o apliquen recursos públicos, realicen actos de autoridad o presten servicios profesionales bajo el régimen de confanza u honorarios y personal de base. El directorio deberá incluir, al menos el nombre, cargo o nombramiento asignado, nivel del puesto en la estructura orgánica, fecha de alta en el cargo, número telefónico, domicilio para recibir correspondencia y dirección de correo electrónico oficiales',1);
INSERT INTO fracciones VALUES (1,8,'Fracción VIII','La remuneración bruta y neta de todos los Servidores Públicos de base o de confanza, con todas las percepciones, incluyendo sueldos, prestaciones, gratificaciones,primas, comisiones, dietas, bonos, estímulos, ingresos y sistemas de compensación, señalando la periodicidad de dicha remuneración;',1);
INSERT INTO fracciones VALUES (1,9,'Fracción IX','Los gastos de representación y viáticos, así como el objeto e informe de comisión correspondiente;',1);
INSERT INTO fracciones VALUES (1,10,'Fracción X','El número total de las plazas y del personal de base y confianza,especificandoel total de las vacantes, por nivel de puesto, para cada unidad administrativa;',1);
INSERT INTO fracciones VALUES (1,11,'Fracción XI','Las contrataciones de servicios profesionales por honorarios, señalando los nombres de los prestadores de servicios, los servicios contratados, el monto de los honorarios y el periodo de contratación;',1);
INSERT INTO fracciones VALUES (1,12,'Fracción XII','La información en Versión Pública de las declaraciones patrimoniales de los Servidores Públicos que así lo determinen, en los sistemas habilitados para ello, de acuerdo a la normatividad aplicable;',1);
INSERT INTO fracciones VALUES (1,13,'Fracción XIII','El domicilio de la Unidad de Transparencia, además de la dirección electrónica donde podrán recibirse las solicitudes para obtener la información;',1);
INSERT INTO fracciones VALUES (1,14,'Fracción XIV','Las convocatorias a concursos para ocupar cargos públicos y los resultados de los mismos;',1);
INSERT INTO fracciones VALUES (1,15,'Fracción XV','La información de los programas de subsidios, estímulos y apoyos, en el que se deberá informar respecto de los programas de transferencia, de servicios, de infraestructura social y de subsidio, en los que se deberá contener lo siguiente:',1);
INSERT INTO fracciones VALUES (1,16,'Fracción XVI','Las condiciones generales de trabajo, contratos o convenios que regulen las relaciones laborales del personal de base o de confianza,así como los recursos públicos económicos, en especie o donativos, que sean entregados a los sindicatos y ejerzan como recursos públicos;',1);
INSERT INTO fracciones VALUES (1,17,'Fracción XVII','La información curricular, desde el nivel de jefe de departamento o equivalente, hasta el titular del Sujeto Obligado, así como, en su caso, las sanciones administrativas de que haya sido objeto;',1);
INSERT INTO fracciones VALUES (1,18,'Fracción XVIII','El listado de Servidores Públicos con sanciones administrativas definitias, especificando la causa de sanción y la disposición',1);
INSERT INTO fracciones VALUES (1,19,'Fracción XIX','Los servicios que ofrecen señalando los requisitos para acceder a ellos;',1);
INSERT INTO fracciones VALUES (1,20,'Fracción XX','Los trámites, requisitos y formatos que ofrecen;',1);
INSERT INTO fracciones VALUES (1,21,'Fracción XXI','La información financierasobre el presupuesto asignado, así como los informes del ejercicio trimestral del gasto, en términos de la Ley General de Contabilidad Gubernamental y demás normatividad aplicable;',1);
INSERT INTO fracciones VALUES (1,22,'Fracción XXI','La información relativa a la deuda pública, en términos de la normatividad aplicable;',1);
INSERT INTO fracciones VALUES (1,23,'Fracción XXIII','Los montos destinados a gastos relativos a comunicación social y publicidad oficialdesglosada por tipo de medio, proveedores, número de contrato y concepto o campaña;',1);
INSERT INTO fracciones VALUES (1,24,'Fracción XXIV','Los informes de resultados de las auditorías al ejercicio presupuestal de cada Sujeto Obligado que se realicen y, en su caso, las aclaraciones que correspondan;',1);
INSERT INTO fracciones VALUES (1,25,'Fracción XXV','El resultado de la dictaminación de los estados financieos;',1);
INSERT INTO fracciones VALUES (1,26,'Fracción XXVI','Los montos, criterios, convocatorias y listado de personas físicas o morales a quienes, por cualquier motivo, se les asigne o permita usar recursos públicos o, en los términos de las disposiciones aplicables, realicen actos de autoridad. Asimismo, los informes que dichas personas les entreguen sobre el uso y destino de dichos recursos;',1);
INSERT INTO fracciones VALUES (1,27,'Fracción XXVII','Las concesiones, contratos, convenios, permisos, licencias o autorizaciones otorgados, especificandolos titulares de aquéllos, debiendo publicarse su objeto, nombre o razón social del titular, vigencia, tipo, términos, condiciones, monto y modificaciones,así como si el procedimiento involucra el aprovechamiento de bienes, servicios y/o recursos públicos;',1);
INSERT INTO fracciones VALUES (1,28,'Fracción XXVIII','La información sobre los resultados sobre procedimientos de adjudicación directa, invitación restringida y licitación de cualquier naturaleza, incluyendo la Versión Pública del Expediente respectivo y de los contratos celebrados, que deberá contener, por lo menos, lo siguiente:',1);
INSERT INTO fracciones VALUES (1,29,'Fracción XXIX','Los informes que por disposición legal generen los Sujetos Obligados;',1);
INSERT INTO fracciones VALUES (1,30,'Fracción XXX','Las estadísticas que generen en cumplimiento de sus facultades, competencias o funciones con la mayor desagregación posible;',1);
INSERT INTO fracciones VALUES (1,31,'Fracción XXXI','Informe de avances programáticos o presupuestales, balances generales y su estado financieo;',1);
INSERT INTO fracciones VALUES (1,32,'Fracción XXXII','Padrón de proveedores y contratistas;',1);
INSERT INTO fracciones VALUES (1,33,'Fracción XXXIII','Los convenios de coordinación y de concertación con los sectores social y privado;',1);
INSERT INTO fracciones VALUES (1,34,'Fracción XXXIV','El inventario de bienes muebles e inmuebles en posesión y propiedad;',1);
INSERT INTO fracciones VALUES (1,35,'Fracción XXXV','Las recomendaciones emitidas por los órganos públicos del Estado mexicano u organismos internacionales garantes de los derechos humanos, así como las acciones que han llevado a cabo para su atención;',1);
INSERT INTO fracciones VALUES (1,36,'Fracción XXXVI','Las resoluciones y laudos que se emitan en procesos o procedimientos seguidos en forma de juicio;',1);
INSERT INTO fracciones VALUES (1,37,'Fracción XXXVII','Los mecanismos de participación ciudadana;',1);
INSERT INTO fracciones VALUES (1,38,'Fracción XXXVIII','Los programas que ofrecen, incluyendo información sobre la población, objetivo y destino, así como los trámites, tiempos de respuesta, requisitos y formatos para acceder a los mismos;',1);
INSERT INTO fracciones VALUES (1,39,'Fracción XXXIX','Las actas y resoluciones del Comité de Transparencia de los Sujetos Obligados;',1);
INSERT INTO fracciones VALUES (1,40,'Fracción XL','Todas las evaluaciones y encuestas que hagan los Sujetos Obligados a programas financiados con ecursos públicos;',1);
INSERT INTO fracciones VALUES (1,41,'Fracción XLI','Los estudios financiados con ecursos públicos;',1);
INSERT INTO fracciones VALUES (1,42,'Fracción XLII','El listado de jubilados y pensionados y el monto que reciben;',1);
INSERT INTO fracciones VALUES (1,43,'Fracción XLIII','Los ingresos recibidos por cualquier concepto, señalando el nombre de los responsables de recibirlos, administrarlos y ejercerlos, así como su destino; indicando el destino de cada uno de ellos;',1);
INSERT INTO fracciones VALUES (1,44,'Fracción XLIV','Donaciones hechas a terceros en dinero o en especie;',1);
INSERT INTO fracciones VALUES (1,45,'Fracción XLV','El catálogo de disposición y guía de archivo documental;',1);
INSERT INTO fracciones VALUES (1,46,'Fracción XLVI','Las actas de sesiones ordinarias y extraordinarias, así como las opiniones y recomendaciones que emitan, en su caso, los consejos consultivos;',1);
INSERT INTO fracciones VALUES (1,47,'Fracción XLVII','Para efectos estadísticos, el listado de solicitudes a las empresas concesionarias de telecomunicaciones y proveedores de servicios o aplicaciones de Internet para la intervención de comunicaciones privadas, el acceso al registro de comunicaciones y la localización geográficaen tiempo real de equipos de comunicación, que contenga exclusivamente el objeto, el alcance temporal y los fundamentos legales del requerimiento, así como, en su caso, la mención que cuenta con la autorización judicial correspondiente;',1);
INSERT INTO fracciones VALUES (1,48,'Fracción XLVIII','Los acuerdos e índices de la información clasificadacomo reservada, en formatos abiertos; y',1);
INSERT INTO fracciones VALUES (1,49,'Fracción XLIX','Cualquier otra información que sea de utilidad o se considere relevante, además de la que, con base en la información estadística, responda a las preguntas hechas con más frecuencia por el público.',1);
INSERT INTO fracciones VALUES (2,50,'Fracción I','El Plan Estatal de Desarrollo y los programas operativos anuales sectoriales; ',1);
INSERT INTO fracciones VALUES (2,51,'Fracción II','El Sistema Integral de Información Financiera;',1);
INSERT INTO fracciones VALUES (2,52,'Fracción III','El Periódico Oficial del Estado;',1);
INSERT INTO fracciones VALUES (2,53,'Fracción IV','El presupuesto de egresos y las fórmulas de distribución de los recursos otorgados;',1);
INSERT INTO fracciones VALUES (2,54,'Fracción V','El listado de expropiaciones decretadas y ejecutadas que incluya, cuando menos, la fecha de expropiación, el domicilio, la causa de utilidad pública y las ocupaciones superficiales',1);
INSERT INTO fracciones VALUES (2,55,'Fracción VI','El nombre, denominación o razón social y clave del Registro Federal de Contribuyentes a los que se les hubiera cancelado o condonado algún crédito fiscal,así como los montos respectivos. Asimismo, la información estadística sobre las exenciones previstas en las disposiciones fiscales',1);
INSERT INTO fracciones VALUES (2,56,'Fracción VII',' Los nombres de las personas a quienes se les habilitó para ejercer como notarios públicos, así como sus datos de contacto, la información relacionada con el proceso de otorgamiento de la patente y las sanciones que se les hubieran aplicado;',1);
INSERT INTO fracciones VALUES (2,57,'Fracción VIII','La información detallada que contengan los planes de desarrollo urbano, ordenamiento territorial y ecológico, los tipos y usos de suelo, licencias de uso y construcción otorgadas; y',1);
INSERT INTO fracciones VALUES (2,58,'Fracción IX','Las disposiciones administrativas, directamente o a través de la autoridad competente, con el plazo de anticipación que prevean las normas aplicables al Sujeto Obligado de que se trate, salvo que su difusión pueda comprometer los efectos que se pretenden lograr con la medida o se trate de situaciones de emergencia, de conformidad con dichas disposiciones.',1);
INSERT INTO fracciones VALUES (3,59,'Fracción I','Los planes y programas de estudio según el sistema que ofrecen, ya sea escolarizado o abierto, con las áreas de conocimiento, el perfilprofesional de quien cursa el plan de estudios, la duración del programa con las asignaturas, su valor en créditos;',1);
INSERT INTO fracciones VALUES (3,60,'Fracción II','Toda la información relacionada con sus procedimientos administrativos;',1);
INSERT INTO fracciones VALUES (3,61,'Fracción III','La remuneración de los profesores, incluyendo los estímulos al desempeño, nivel y monto;',1);
INSERT INTO fracciones VALUES (3,62,'Fracción IV','La lista con los profesores con licencia o en año sabático;',1);
INSERT INTO fracciones VALUES (3,63,'Fracción V','El listado de las becas y apoyos que otorgan, así como los procedimientos y requisitos para obtenerlos;',1);
INSERT INTO fracciones VALUES (3,64,'Fracción VI','Las convocatorias de los concursos de oposición;',1);
INSERT INTO fracciones VALUES (3,65,'Fracción VII',' La información relativa a los procesos de selección de los consejos;',1);
INSERT INTO fracciones VALUES (3,66,'Fracción VIII','Resultado de las evaluaciones del cuerpo docente; y',1);
INSERT INTO fracciones VALUES (3,67,'Fracción IX','El listado de instituciones incorporadas y requisitos de incorporación.',1);
INSERT INTO incisos VALUES(1,15,1,'a) Área;',1);
INSERT INTO incisos VALUES(1,15,2,'b) Denominación del programa;',1);
INSERT INTO incisos VALUES(1,15,3,'c) Periodo de vigencia;',1);
INSERT INTO incisos VALUES(1,15,4,'d) Diseño, objetivos y alcances;',1);
INSERT INTO incisos VALUES(1,15,5,'e) Metas físicas;',1);
INSERT INTO incisos VALUES(1,15,6,'f) Población beneficiada estimada',1);
INSERT INTO incisos VALUES(1,15,7,'g) Monto aprobado, modificdo y ejercido, así como los calendarios de su programación presupuestal;',1);
INSERT INTO incisos VALUES(1,15,8,'h) Requisitos y procedimientos de acceso;',1);
INSERT INTO incisos VALUES(1,15,9,'i) Procedimiento de queja o inconformidad ciudadana;',1);
INSERT INTO incisos VALUES(1,15,10,'j) Mecanismos de exigibilidad;',1);
INSERT INTO incisos VALUES(1,15,11,'k) Mecanismos de evaluación, informes de evaluación y seguimiento de recomendaciones;',1);
INSERT INTO incisos VALUES(1,15,12,'l) Indicadores con nombre, definición,método de cálculo, unidad de medida, dimensión, frecuencia de medición, nombre de las bases de datos utilizadas para su cálculo;',1);
INSERT INTO incisos VALUES(1,15,13,'m) Formas de participación social;',1);
INSERT INTO incisos VALUES(1,15,14,'n) Articulación con otros programas sociales;',1);
INSERT INTO incisos VALUES(1,15,15,'o) Vínculo a las reglas de operación o Documento equivalente;',1);
INSERT INTO incisos VALUES(1,15,16,'p) Informes periódicos sobre la ejecución y los resultados de las evaluaciones realizadas; y',1);
INSERT INTO incisos VALUES(1,15,17,'q) Padrón de beneficiarios,mismo que deberá contener los siguientes datos: nombre de la persona física o denominación social de las personas jurídicas colectivas beneficiarias,el monto, recurso, beneficioo apoyo otorgado para cada una de ellas, unidad territorial, en su caso, edad y sexo;',1);
INSERT INTO incisos VALUES(1,28,18,'a) De licitaciones públicas o procedimientos de invitación restringida:',1);
INSERT INTO incisos VALUES(1,28,19,'b) De las adjudicaciones directas:',1);
INSERT INTO apartados VALUES (1,28,18,1,'1. La convocatoria o invitación emitida, así como los fundamentos legales aplicados para llevarla a cabo;',1);
INSERT INTO apartados VALUES (1,28,18,2,'2. Los nombres de los participantes o invitados;',1);
INSERT INTO apartados VALUES (1,28,18,3,'3. El nombre del ganador y las razones que lo justifican',1);
INSERT INTO apartados VALUES (1,28,18,4,'4. El área solicitante y la responsable de su ejecución;',1);
INSERT INTO apartados VALUES (1,28,18,5,'5. Las convocatorias e invitaciones emitidas;',1);
INSERT INTO apartados VALUES (1,28,18,6,'6. Los dictámenes y fallo de adjudicación;',1);
INSERT INTO apartados VALUES (1,28,18,7,'7. El contrato y, en su caso, sus anexos;',1);
INSERT INTO apartados VALUES (1,28,18,8,'8. Los mecanismos de vigilancia y supervisión, incluyendo, en su caso, los estudios de impacto urbano y ambiental, según corresponda;',1);
INSERT INTO apartados VALUES (1,28,18,9,'9. La partida presupuestal, de conformidad con el clasificadorpor objeto del gasto, en el caso de ser aplicable;',1);
INSERT INTO apartados VALUES (1,28,18,10,'10. Origen de los recursos especificandosi son federales, estatales o municipales, así como el tipo de fondo de participación o aportación respectiva;',1);
INSERT INTO apartados VALUES (1,28,18,11,'11. Los convenios modificaorios que, en su caso, sean firados, precisando el objeto y la fecha de celebración;',1);
INSERT INTO apartados VALUES (1,28,18,12,'12. Los informes de avance físico y financieo sobre las obras o servicios contratados;',1);
INSERT INTO apartados VALUES (1,28,18,13,'13. El convenio de terminación; y',1);
INSERT INTO apartados VALUES (1,28,18,14,'14. El finiquio;',1);
INSERT INTO apartados VALUES (1,28,19,15,'1. La propuesta enviada por el participante;',1);
INSERT INTO apartados VALUES (1,28,19,16,'2. Los motivos y fundamentos legales aplicados para llevarla a cabo;',1);
INSERT INTO apartados VALUES (1,28,19,17,'3. La autorización del ejercicio de la opción;',1);
INSERT INTO apartados VALUES (1,28,19,18,'4. En su caso, las cotizaciones consideradas, especificandolos nombres de los proveedores y los montos;',1);
INSERT INTO apartados VALUES (1,28,19,19,'5. El nombre de la persona física o jurídica colectiva adjudicada;',1);
INSERT INTO apartados VALUES (1,28,19,20,'6. La unidad administrativa solicitante y la responsable de su ejecución;',1);
INSERT INTO apartados VALUES (1,28,19,21,'7. El número, fecha, el monto del contrato y el plazo de entrega o de ejecución de los servicios u obra;',1);
INSERT INTO apartados VALUES (1,28,19,22,'8. Los mecanismos de vigilancia y supervisión, incluyendo, en su caso, los estudios de impacto urbano y ambiental, según corresponda;',1);
INSERT INTO apartados VALUES (1,28,19,23,'9. Los informes de avance sobre las obras o servicios contratados;',1);
INSERT INTO apartados VALUES (1,28,19,24,'10. El convenio de terminación; y',1);
INSERT INTO apartados VALUES (1,28,19,25,'11. El finiquio.',1);
INSERT INTO AREAS VALUES (1,'Dirección de Informática',1);
INSERT INTO AREAS VALUES (2,'Abogado General',1);
INSERT INTO AREAS VALUES (3,'Dirección de Adinistración y Finanzas',1);
INSERT INTO AREAS VALUES (4,'Dirección de Planeación y Evaluación',1);
INSERT INTO AREAS VALUES (5,'Contraloria Interna',1);
INSERT INTO AREAS VALUES (6,'Unidad de Acceso a la Información',1);
INSERT INTO AREAS VALUES (7,'Dirección de Servicios Escolares',1);
INSERT INTO AREAS VALUES (8,'Secretaría Académica',1);
INSERT INTO AREAS VALUES (9,'Secretaría de Vinculación',1);
INSERT INTO AREAS VALUES (10,'Unidad de Mejora Continua',1);
INSERT INTO AREAS VALUES (11,'Departamento de Recursos Materiales',1);
INSERT INTO AREAS VALUES (12,'Departamento de Recursos Humanos',1);
INSERT INTO AREAS VALUES (13,'Departamento de Programación y Presupuesto',1);
INSERT INTO AREAS VALUES (14,'Departamento de Contabilidad',1);
INSERT INTO AREAS VALUES (15,'Dirección de Servicios Especializados',1);
INSERT INTO AREAS VALUES (16,'Dirección de Enlace Empresarial',1);
INSERT INTO AREAS VALUES (17,'Dirección de Difusión Universitaria',1);
INSERT INTO AREAS VALUES (18,'Nominaconvenios',1);
INSERT INTO AREAS VALUES (19,'Unidad de Promoción Universitaria',1);
INSERT INTO AREAS VALUES (20,'Centro de atención al Sector Energetico',1);
INSERT INTO AREAS VALUES (21,'Departamento de Mantenimiento',1);
INSERT INTO usuarios VALUES(1,1,'Roberto Eder Weiss Juárez','eder.weiss87','sbcz YLm',1);
INSERT INTO usuarios VALUES(2,1,'David León Baeza','virus','_br_Fsn)9K',1);
INSERT INTO usuarios VALUES(3,1,'Jorge José Jiménez Del Cueto','cuetox','o)mK¿Yn3',1);
INSERT INTO usuarios VALUES(4,1,'Juan Alberto Camacho Ochoa','jaco',':b_bÑbr_',1);
INSERT INTO usuarios VALUES(5,2,'Paulino Zapata Arias','abogadogral@uttab.edu.mx','2K3cÑ:Ae',1);
INSERT INTO usuarios VALUES(6,3,'Sergio Hermilo Jiménez Torres','administracion@uttab.edu.mx','W?ñeÑc_6f',1);
INSERT INTO usuarios VALUES(7,4,'Piotr Aleksander Dobrusin Ziemba','d.planeacion@uttab.edu.mx','4m:ñ_ c_',1);
INSERT INTO usuarios VALUES(8,5,'Roberto Ordóñez Herrera','contraloria@uttab.edu.mx','BKANIIO66',1);
INSERT INTO usuarios VALUES(9,6,'Rigoberto Ochoa Murillo','transparencia@uttab.edu.mx','PmtcÑcOe',1);
INSERT INTO usuarios VALUES(10,7,'Lorena Rodríguez Juárez','d.escolares@uttab.edu.mx','J¡ñ_fjc_',1);
INSERT INTO usuarios VALUES(11,8,'Sergio Octavio Valle Mijangos','academica@uttab.edu.mx','Z?jñXz:d',1);
INSERT INTO usuarios VALUES(12,9,'Ricardo Amado Moheno Barrueta','vinculacion@uttab.edu.mx','.KjNssXz',1);
INSERT INTO usuarios VALUES(13,10,'Consuelo León Peralta','mejoracontinua@uttab.edu.mx','hL)ñ6:jb',1);
INSERT INTO usuarios VALUES(14,11,'Jesús Baeza Vidal','rec.mat@uttab.edu.mx','-¡YHO66_',1);
INSERT INTO usuarios VALUES(15,12,'Alfonso Boylan León','rhumanos@uttab.edu.mx',',oA __ñv',1);
INSERT INTO usuarios VALUES(16,13,'José Mauricio Alarcón Román','presupuesto@uttab.edu.mx','2¡ssXz:d',1);
INSERT INTO usuarios VALUES(17,14,'Sonia del Carmen Pérez Gallegos','contabilidad@uttab.edu.mx','y¿rIIGd_',1);
INSERT INTO usuarios VALUES(18,15,'Laura Beatriz Guzmán Priego','d.especializados@uttab.edu.mx','Jmfjc_dG',1);
INSERT INTO usuarios VALUES(19,16,'Australia Vallejo Hidalgo','d.desarrollo@uttab.edu.mx','4¡O66:jb',1);
INSERT INTO usuarios VALUES(20,17,'Lenin González Baños','d.euniversitaria@uttab.edu.mx','yKrIIAA ',1);
INSERT INTO usuarios VALUES(21,18,'Nominaconvenios','nominaproyectos@uttab.edu.mx','J¿GNHñfj',1);
INSERT INTO usuarios VALUES(22,19,'Xanath Alexandra Rebolledo González','unidaddepromocion@uttab.edu.mx','q¡c_XNrY ',1);
INSERT INTO usuarios VALUES(23,20,'Guillermo Oliver González Rodríguez','case@uttab.edu.mx','4mr_tÑ3 ',1);
INSERT INTO usuarios VALUES(24,21,'Sergio Aníbal Contreras Carrillo','mantenimiento@uttab.edu.mx',',¡c :Ys_',1);